function [param_list, param_struct] = pvcamparlist(h_cam)

% PVCAMPARLIST - obtain PVCAM parameter values
%
%   SYNTAX:  [LIST, STRUCT] = PVCAMPARLIST(HCAM)

% 5/28/04 SCM
% parameter list obtained from PVCAM.H
% parameter list current for PVCAM version 2.6.9
% need to update this list when newer PVCAM version used

% create parameter list
param_list = sort({ ...
        'PARAM_DD_INFO', ...
        'PARAM_DD_INFO_LENGTH', ...
        'PARAM_DD_VERSION', ...
        'PARAM_DD_RETRIES', ...
        'PARAM_DD_TIMEOUT', ...
        'PARAM_MIN_BLOCK', ...
        'PARAM_NUM_MIN_BLOCK', ...
        'PARAM_SKIP_AT_ONCE_BLK', ...
        'PARAM_NUM_OF_STRIPS_PER_CLR', ...
        'PARAM_CONT_CLEARS', ...
        'PARAM_ANTI_BLOOMING', ...
        'PARAM_LOGIC_OUTPUT', ...
        'PARAM_EDGE_TRIGGER', ...
        'PARAM_INTENSIFIER_GAIN', ...
        'PARAM_SHTR_GATE_MODE', ...
        'PARAM_ADC_OFFSET', ...
        'PARAM_CHIP_NAME', ...
        'PARAM_COOLING_MODE', ...
        'PARAM_PREAMP_DELAY', ...
        'PARAM_PREFLASH', ...
        'PARAM_COLOR_MODE', ...
        'PARAM_MPP_CAPABLE', ...
        'PARAM_PREAMP_OFF_CONTROL', ...
        'PARAM_SERIAL_NUM', ...
        'PARAM_PREMASK', ...
        'PARAM_PRESCAN', ...
        'PARAM_POSTMASK', ...
        'PARAM_POSTSCAN', ...
        'PARAM_PIX_PAR_DIST', ...
        'PARAM_PIX_PAR_SIZE', ...
        'PARAM_PIX_SER_DIST', ...
        'PARAM_PIX_SER_SIZE', ...
        'PARAM_SUMMING_WELL', ...
        'PARAM_FWELL_CAPACITY', ...
        'PARAM_PAR_SIZE', ...
        'PARAM_SER_SIZE', ...
        'PARAM_ACCUM_CAPABLE', ...
        'PARAM_FLASH_DWNLD_CAPABLE', ...
        'PARAM_CONTROLLER_ALIVE', ...
        'PARAM_READOUT_TIME', ...
        'PARAM_CLEAR_CYCLES', ...
        'PARAM_CLEAR_MODE', ...
        'PARAM_FRAME_CAPABLE', ...
        'PARAM_PMODE', ...
        'PARAM_CCS_STATUS', ...
        'PARAM_TEMP', ...
        'PARAM_TEMP_SETPOINT', ...
        'PARAM_CAM_FW_VERSION', ...
        'PARAM_HEAD_SER_NUM_ALPHA', ...
        'PARAM_PCI_FW_VERSION', ...
        'PARAM_CAM_FW_FULL_VERSION', ...
        'PARAM_EXPOSURE_MODE', ...
        'PARAM_BIT_DEPTH', ...
        'PARAM_GAIN_INDEX', ...
        'PARAM_SPDTAB_INDEX', ...
        'PARAM_READOUT_PORT', ...
        'PARAM_PIX_TIME', ...
        'PARAM_SHTR_CLOSE_DELAY', ...
        'PARAM_SHTR_OPEN_DELAY', ...
        'PARAM_SHTR_OPEN_MODE', ...
        'PARAM_SHTR_STATUS', ...
        'PARAM_SHTR_CLOSE_DELAY_UNIT', ...
        'PARAM_IO_ADDR', ...
        'PARAM_IO_TYPE', ...
        'PARAM_IO_DIRECTION', ...
        'PARAM_IO_STATE', ...
        'PARAM_IO_BITDEPTH', ...
        'PARAM_GAIN_MULT_FACTOR', ...
        'PARAM_GAIN_MULT_ENABLE', ...
        'PARAM_EXP_TIME', ...
        'PARAM_EXP_RES', ...
        'PARAM_EXP_MIN_TIME', ...
        'PARAM_EXP_RES_INDEX', ...
        'PARAM_BOF_EOF_ENABLE', ...
        'PARAM_BOF_EOF_COUNT', ...
        'PARAM_BOF_EOF_CLR', ...
        'PARAM_CIRC_BUFFER', ...
        'PARAM_HW_AUTOSTOP', ...
    });

param_struct = cell(1, numel(param_list));
for i = 1 : numel(param_list)
    param_struct{i} = pvcamget(h_cam, param_list{i});
end
return
